name: New Sentry Release
on:
  release:
    types: [published]
jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: discordextremelist/sentry-releases-action@v1.2.3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: discord-extreme-list
          SENTRY_PROJECT: website
        with:
          tagName: ${{ GITHUB_REF#refs/tags/ }}
